In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [6]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
### Create an array of zeros with 2 rows and 10 columns

In [20]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(3,2)

array([[7.12215251e-01, 8.99358901e-01],
       [5.73167142e-01, 4.38550369e-01],
       [6.13945697e-04, 9.89051096e-01]])

In [25]:
np.random.randn(3,2)

array([[-1.49921174, -0.67567056],
       [-0.08050019, -1.04178799],
       [ 2.72739654, -0.32205442]])

In [26]:
np.random.randint(34.100)

31

In [27]:
np.random.randint(34,100,50)

array([95, 66, 80, 36, 61, 81, 60, 69, 94, 44, 58, 48, 96, 69, 52, 35, 42,
       58, 56, 36, 46, 34, 88, 56, 56, 47, 61, 88, 34, 72, 47, 64, 89, 90,
       71, 94, 78, 74, 93, 72, 58, 75, 55, 95, 61, 52, 52, 96, 66, 82])

In [28]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
rand_array=np.random.randint(0,100,20)
rand_array

array([65, 33, 28, 95, 47, 80, 26, 29, 27, 95, 19, 54, 42, 50, 82, 77, 52,
       47, 95,  5])

In [30]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
rand_array.min()

5

In [32]:
rand_array.argmin()

19

In [33]:
sample_array.dtype

dtype('int64')

In [35]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array[3]

13

In [40]:
sample_array[3:7]

array([13, 14, 15, 16])

In [42]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [47]:
subset_sample_array[1:4]=1001
subset_sample_array

array([1001, 1001, 1001, 1001,   14,   15,   16])

In [48]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

Two dimensional array

In [49]:
import numpy as np

In [50]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,42,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 42,  7]])

In [51]:
sample_matrix[0:2,2]

array([ 1, 21])

In [52]:
sample_matrix[2,:]

array([56, 76, 42,  7])

In [53]:
sample_matrix[2]

array([56, 76, 42,  7])

In [54]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 42]])

In [55]:
sample_array=np.arange(1,20)

In [56]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [57]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [58]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [59]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [61]:
np.max(sample_array)

19

In [63]:
np.min(sample_array)

1

In [64]:
np.argmax(sample_array)

18

In [65]:
np.argmin(sample_array)

0

In [66]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [67]:
np.std(sample_array)

5.477225575051661

In [68]:
np.var(sample_array)

30.0

In [69]:
np.mean(sample_array)

10.0

In [72]:
array=np.random.randn(3,4)
array

array([[ 1.32626057, -2.55209838, -1.2512623 , -0.85487887],
       [ 0.70520096,  2.02222775,  0.280567  , -0.93425706],
       [-0.03164105,  0.70236102, -1.61130804,  0.47391578]])

In [74]:
np.round(array,decimals=3)

array([[ 1.326, -2.552, -1.251, -0.855],
       [ 0.705,  2.022,  0.281, -0.934],
       [-0.032,  0.702, -1.611,  0.474]])

In [75]:
sports=np.array(['golf','cricket','fball','cricket','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')